[build]
  command = "npm run build"
  publish = "dist"

[[edge_functions]]
  path = "/.netlify/edge-functions/generateImage"
  function = "generateImage"
  # Increase timeout to 20 seconds for image generation
  timeout = 20

[[edge_functions]]
  path = "/.netlify/edge-functions/analyzeImage"
  function = "analyzeImage"

[build.environment]
  NODE_VERSION = "18"

# SPA routing support
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200